services:
  - type: web
    name: django-blog
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: AWS_S3_REGION_NAME
        value: eu-north-1
