services:
  - type: web
    name: django-blog
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn django_project.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: django-blog.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://django-blog.onrender.com
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        value: eu-north-1
