# Generated by Django 5.2.15 on 2026-07-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_posted"]},
        ),
    ]
